plugins {
	id 'eclipse'
	id 'idea'
	id 'maven-publish'
	id 'net.minecraftforge.gradle' version '[6.0.24,6.2)'
	id 'org.parchmentmc.librarian.forgegradle' version '1.+'
	id 'org.spongepowered.mixin' version '0.7.+'
	id 'com.peak885.jarjar-alternative' version '1.2-BETA'
	id 'com.gradleup.shadow' version '9.4.2'
}

group = project.maven_group
version = "${mod_version}+${minecraft_version}"

base {
	archivesName = archives_base_name
}

java {
	toolchain.languageVersion = JavaLanguageVersion.of(21)
	withSourcesJar()
}

minecraft {
	mappings channel: mapping_channel, version: "${mapping_version}-${minecraft_version}"
	copyIdeResources = true

	runs {
		configureEach {
			workingDirectory project.file('run')

			property 'forge.logging.markers', 'REGISTRIES'
			property 'forge.logging.console.level', 'debug'
			property 'mixin.env.remapRefMap', 'true'

			mods {
				libguifoxified {
					source sourceSets.main
				}
			}
		}

		client {}
		server { args '--nogui' }
	}
}

repositories {
	mavenCentral()

	flatDir { dirs 'libs' }
	maven {url "https://raw.githubusercontent.com/peaksuperior885/peaks_maven/main/files/" }

	maven { url "https://jitpack.io" }
	maven { url "https://maven.su5ed.dev/releases" }

	maven {
		url "https://server.bbkr.space/artifactory/libs-release"
		content { includeGroup "io.github.cottonmc" }
	}
}

mixin {
	add sourceSets.main, "libgui.refmap.json"
	config "mixins.libgui.json"
}

configurations {
	bundle
	implementation.extendsFrom bundle
}

dependencies {
	minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

	jarjar('com.peak885.janksonforgified:Jankson-Forgified:6.0.0+j1.2.3+mc1.21.1') { transitive = false }

	bundle "blue.endless:jankson:1.2.3"
	bundle "com.github.TexBlock:LibNinePatch:master-SNAPSHOT"

	annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

tasks.shadowJar {
	dependsOn tasks.getByName("jarjar-alternative")

	archiveClassifier.set('')
	configurations = [project.configurations.bundle]

	from(tasks.getByName("jarjar-alternative").outputs.files.singleFile) {
		into 'META-INF/jarjar'
	}

	relocate 'blue.endless', "${maven_group}.bundle.jankson"
	relocate 'juuxel.libninepatch', "${maven_group}.bundle.ninepatch"

	dependencies {
		exclude(dependency('org.jetbrains.kotlin:.*'))
		exclude(dependency('org.slf4j:.*'))
		exclude(dependency('net.sf.jopt-simple:.*'))
		exclude(dependency('com.google.code.gson:gson:.*'))
	}

	exclude 'kotlin/**'
	exclude 'kotlinx/**'
	exclude 'META-INF/kotlin*'
	exclude 'META-INF/versions/**'
}

tasks.build.dependsOn shadowJar

jar {
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE

	manifest {
		attributes(
			'Specification-Title': 'libguifoxified',
			'Specification-Version': '1',
			'Implementation-Title': project.name,
			'Implementation-Version': project.version,
			'MixinConfigs': 'mixins.libgui.json'
		)
	}
}

processResources {
	filesMatching(['META-INF/mods.toml', 'mixins.libgui.json']) {
		expand(version: project.version, project: project)
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
	options.release = 21
}

tasks.withType(JavaCompile).configureEach {
	doFirst {
		println "Compile classpath:"
		classpath.files.each { println "  $it" }
	}
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}
}
